### PR TITLE
Change edit command syntax

### PR DESCRIPTION
**Pull request by darrenwee**
Change `edit` command syntax to something more intuitive.

### CODE REVIEW

**Comment by craaaa** [comment]
what is the new syntax?

**Comment by darrenwee** [comment]
``` bash
# old syntax
for CONTEXT_ID edit FIELD_NAME:NEW_DETAIL

# new syntax
edit CONTEXT_ID FIELD_NAME:NEW_DETAIL

## same thing for EVENT_ID
```

As per Muthu's comments in tutorial. Only the user guide is updated, though, not the actual `EditCommand` class.

**Comment by yyc** [comment]
I'll merge this in with the actual changes to EditCommand. I'll get on it if noone else is doing it.

**Comment by darrenwee** [comment]
`EditCommand` has been updated to reflect the new syntax and to make persistent edits in the `add-edit-command` branch. Will wait for Duc to finish the undo for `edit` and then we can include the user guide change in that branch instead of this one.

**Pull request closed without merging**
