### PR TITLE
Update user guide for v0.3

### PR DESCRIPTION
**Pull request by darrenwee**

### CODE REVIEW

**Review by craaaa — COMMENTED** [review]
- Is there a need for both `event_id` and `context_id`?
- How to differentiate between event_id and context_id when parsing commands?
- I don't understand the table about field names: do they require specific types? what are they there for?
- Is the syntax for all tasks `add EVENT_NAME from DATETIME` or `add EVENT_NAME from DATETIME to DATETIME`
- Change description of find command to include finding by index

**Comment by craaaa** [comment]
Oops ignore the bit about the help command

**Comment by darrenwee** [comment]
> Is there a need for both event_id and context_id?

Context ID is the user-friendly identifier which is dependent on the agenda pane of the UI and not persistent. Event ID is unique and persistent. We leave both implemented for completeness sake.

> How to differentiate between event_id and context_id when parsing commands?

Numerical range of `context_id` and `event_id` should not overlap, e.g. `context_id` in [0,10] while `event_id` in [100, infinity). They are then differentiated by their magnitudes which is easy to check.

> I don't understand the table about field names: do they require specific types? what are they there for?

They are enums. For example, if you want to change the item name field, you must specify the field name as `name` in the `edit` command. The type column denotes what type of field format it expects. This is for the user's information so that they don't try to give silly input. For example, you cannot give a non-datetime input:

``` bash
# this should fail because "dog" and "giraffe" don't contain any date/time tokens
for 1 edit start: dog, end: giraffe
```

> Is the syntax for all tasks add EVENT_NAME from DATETIME or add EVENT_NAME from DATETIME to DATETIME

`DATETIME` can be in the form of a period like `from today to three days from now` (as outlined in Field Formats -> `datetime`).

The reason I did not specify it as `DATETIME to DATETIME` was to avoid restricting the choice of conjunction (whatever you call "to" in grammar) so you can also enter stuff like `from today till three days from now` without the word "to".

On the other hand, the one for deadline has the word `by` outside of the `DATETIME` field because the range of elicitations for a `DATETIME` as a deadline is narrower. (does this make sense idk i'm tired)

Do you think we should clarify the adding event command in the guide? @craaaa 

> Change description of find command to include finding by index

Fixed!

**Review by craaaa — APPROVED** [review]
LOOKS GOOD TO ME!

**Pull request merged**
